name: app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=3.3.4 <4.0.0"
  # ">=3.2.6 <4.0.0"

# Packages - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dependencies:
  address_search_field: ^5.0.3
  animate_do: ^3.3.4
  connectivity_plus: ^5.0.2
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.2
  dash_chat_2: ^0.0.20
  easy_stepper: ^0.8.3
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_native_splash: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^0.13.5
  iconsax: ^0.0.8
  intl: ^0.18.0
  liquid_swipe: ^3.1.0
  page_transition: ^2.1.0
  rename: ^3.0.1
  search_field_autocomplete: ^1.0.0
  timelines: ^0.1.0
  url_launcher: ^6.2.5
  web: 0.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/navigation_bar_svg/
    - assets/images/home/
    - assets/images/profile/

  # Fonts - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
